#day2
a=[1,2,3,4,"phani"]
b=("swathi",1,2,3,4,4.8,"dhanu","nanna")
c={"name":"krishna","age":20,"class":"B.Tech.","Grade":"A","Section":"Theta"}
print(a)
print(b)
print(c)
print(a[3])
print(b[0])
print(c["Section"])
